---
# Playbook to locally test the role.
# Run from the repository root:
# ansible-playbook -i inventory local-playbook.yml -K

- name: Setup Debian systems - local tests.
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - {role: ../constructor}